services:
  next-app:
    environment:
      # FIXME: WSLのバグか何かでNODE_ENV: developでhot reloadが即座に効かないらしいので一次しのぎ
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    command: npm run dev

  python-app:
    environment:
      APP_ENV: development
    volumes:
      - ./backend/api:/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
