services:
  # frontend
  next-app:
    container_name: next-app
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  # backend
  python-app:
    container_name: python-app
    build:
      context: ./backend
    environment:
      APP_ENV: production
    ports:
      - 8000:8000
    volumes:
      - ./backend/api:/src
