import { CorporateDetailList } from "@/api/corporate/ResTypes";

/** TODO: 使い終わったら消す */
export const sampleData: CorporateDetailList = [
  {
    businessItems: ["ITコンサルティング", "ソフトウェア開発"],
    businessSummary:
      "IT関連のコンサルティングおよびソフトウェア開発を行う企業。",
    capitalStock: 50000000,
    certification: [
      {
        category: "ISO 9001",
        dateOfApproval: "2019-04-01",
        enterpriseScale: "中小企業",
        expirationDate: "2022-03-31",
        governmentDepartments: "日本品質保証機構",
        target: "全社",
        title: "品質管理システム",
      },
    ],
    closeCause: "",
    closeDate: "",
    commendation: [
      {
        category: "技術賞",
        dateOfCommendation: "2021-10-15",
        governmentDepartments: "経済産業省",
        target: "開発チーム",
        title: "革新技術賞",
      },
    ],
    companySizeFemale: 25,
    companySizeMale: 45,
    companyUrl: "https://www.tech-consulting.jp",
    corporateNumber: "1010001084833",
    dateOfEstablishment: "2010-05-12",
    employeeNumber: 70,
    finance: {
      accountingStandards: "日本基準",
      fiscalYearCoverPage: "2021",
      majorShareholders: [
        {
          nameMajorShareholders: "田中太郎",
          shareholdingRatio: 40,
        },
      ],
      managementIndex: [
        {
          capitalStockSummaryOfBusinessResults: 50000000,
          capitalStockSummaryOfBusinessResultsUnitRef: "JPY",
          grossOperatingRevenueSummaryOfBusinessResults: 200000000,
          grossOperatingRevenueSummaryOfBusinessResultsUnitRef: "JPY",
          netAssetsSummaryOfBusinessResults: 100000000,
          netAssetsSummaryOfBusinessResultsUnitRef: "JPY",
          netIncomeLossSummaryOfBusinessResults: 5000000,
          netIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          netPremiumsWrittenSummaryOfBusinessResultsIns: 0,
          netPremiumsWrittenSummaryOfBusinessResultsInsUnitRef: "JPY",
          netSalesSummaryOfBusinessResults: 200000000,
          netSalesSummaryOfBusinessResultsUnitRef: "JPY",
          numberOfEmployees: 70,
          numberOfEmployeesUnitRef: "人",
          operatingRevenue1SummaryOfBusinessResults: 180000000,
          operatingRevenue1SummaryOfBusinessResultsUnitRef: "JPY",
          operatingRevenue2SummaryOfBusinessResults: 20000000,
          operatingRevenue2SummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeLossSummaryOfBusinessResults: 5000000,
          ordinaryIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeSummaryOfBusinessResults: 5000000,
          ordinaryIncomeSummaryOfBusinessResultsUnitRef: "JPY",
          period: "2021-04-01 to 2022-03-31",
          totalAssetsSummaryOfBusinessResults: 150000000,
          totalAssetsSummaryOfBusinessResultsUnitRef: "JPY",
        },
      ],
    },
    foundingYear: 2010,
    kana: "テックコンサルティング",
    location: "東京都千代田区丸の内２丁目４番１号",
    name: "株式会社テックコンサルティング",
    nameEn: "Tech Consulting Inc.",
    numberOfActivity: "0",
    patent: [
      {
        applicationDate: "2020-08-10",
        applicationNumber: "2020-123456",
        classifications: [],
        patentType: "発明",
        title: "AIを用いたデータ解析システム",
      },
    ],
    postalCode: "1000005",
    procurement: [
      {
        amount: 10000000,
        dateOfOrder: "2021-09-15",
        governmentDepartments: "総務省",
        jointSignatures: ["株式会社システムデザイン"],
        title: "新規プロジェクト",
      },
    ],
    qualificationGrade: "A",
    representativeName: "田中太郎",
    representativePosition: "代表取締役",
    status: "運営中",
    subsidy: [
      {
        amount: "5000000",
        dateOfApproval: "2021-05-20",
        governmentDepartments: "経済産業省",
        jointSignatures: ["株式会社サポートエンジニアリング"],
        note: "新規技術開発のための補助金",
        subsidyResource: "国庫",
        target: "開発チーム",
        title: "技術開発補助金",
      },
    ],
    updateDate: "2023-07-01",
    workplaceInfo: {
      baseInfos: {
        averageAge: 35.5,
        averageContinuousServiceYears: 7,
        averageContinuousServiceYearsFemale: 6,
        averageContinuousServiceYearsMale: 8,
        averageContinuousServiceYearsType: "中央値",
        monthAveragePredeterminedOvertimeHours: 10,
      },
      compatibilityOfChildcareAndWork: {
        maternityLeaveAcquisitionNum: 5,
        numberOfMaternityLeave: 5,
        numberOfPaternityLeave: 2,
        paternityLeaveAcquisitionNum: 2,
      },
      womenActivityInfos: {
        femaleShareOfManager: 20,
        femaleShareOfOfficers: 10,
        femaleWorkersProportion: 35,
        femaleWorkersProportionType: "割合",
        genderTotalOfManager: 10,
        genderTotalOfOfficers: 5,
      },
    },
  },
  {
    businessItems: ["金融サービス", "保険"],
    businessSummary: "総合金融サービスを提供する企業。",
    capitalStock: 100000000,
    certification: [
      {
        category: "ISO 27001",
        dateOfApproval: "2020-03-15",
        enterpriseScale: "大企業",
        expirationDate: "2023-03-14",
        governmentDepartments: "情報セキュリティ認証機構",
        target: "全社",
        title: "情報セキュリティ管理システム",
      },
    ],
    closeCause: "",
    closeDate: "",
    commendation: [
      {
        category: "サービス賞",
        dateOfCommendation: "2022-06-20",
        governmentDepartments: "金融庁",
        target: "カスタマーサービス部門",
        title: "顧客満足度No.1",
      },
    ],
    companySizeFemale: 150,
    companySizeMale: 200,
    companyUrl: "https://www.financial-services.jp",
    corporateNumber: "2010002094834",
    dateOfEstablishment: "1985-07-15",
    employeeNumber: 350,
    finance: {
      accountingStandards: "日本基準",
      fiscalYearCoverPage: "2021",
      majorShareholders: [
        {
          nameMajorShareholders: "鈴木一郎",
          shareholdingRatio: 25,
        },
      ],
      managementIndex: [
        {
          capitalStockSummaryOfBusinessResults: 100000000,
          capitalStockSummaryOfBusinessResultsUnitRef: "JPY",
          grossOperatingRevenueSummaryOfBusinessResults: 500000000,
          grossOperatingRevenueSummaryOfBusinessResultsUnitRef: "JPY",
          netAssetsSummaryOfBusinessResults: 300000000,
          netAssetsSummaryOfBusinessResultsUnitRef: "JPY",
          netIncomeLossSummaryOfBusinessResults: 20000000,
          netIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          netPremiumsWrittenSummaryOfBusinessResultsIns: 0,
          netPremiumsWrittenSummaryOfBusinessResultsInsUnitRef: "JPY",
          netSalesSummaryOfBusinessResults: 500000000,
          netSalesSummaryOfBusinessResultsUnitRef: "JPY",
          numberOfEmployees: 350,
          numberOfEmployeesUnitRef: "人",
          operatingRevenue1SummaryOfBusinessResults: 450000000,
          operatingRevenue1SummaryOfBusinessResultsUnitRef: "JPY",
          operatingRevenue2SummaryOfBusinessResults: 50000000,
          operatingRevenue2SummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeLossSummaryOfBusinessResults: 20000000,
          ordinaryIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeSummaryOfBusinessResults: 20000000,
          ordinaryIncomeSummaryOfBusinessResultsUnitRef: "JPY",
          period: "2021-04-01 to 2022-03-31",
          totalAssetsSummaryOfBusinessResults: 600000000,
          totalAssetsSummaryOfBusinessResultsUnitRef: "JPY",
        },
      ],
    },
    foundingYear: 1985,
    kana: "フィナンシャルサービス",
    location: "東京都港区赤坂１丁目２番３号",
    name: "フィナンシャルサービス株式会社",
    nameEn: "Financial Services Inc.",
    numberOfActivity: "0",
    patent: [
      {
        applicationDate: "2019-11-20",
        applicationNumber: "2019-234567",
        classifications: [],
        patentType: "発明",
        title: "自動保険請求システム",
      },
    ],
    postalCode: "1070052",
    procurement: [
      {
        amount: 20000000,
        dateOfOrder: "2021-12-10",
        governmentDepartments: "財務省",
        jointSignatures: ["株式会社リスクマネジメント"],
        title: "新規システム導入",
      },
    ],
    qualificationGrade: "A",
    representativeName: "鈴木一郎",
    representativePosition: "代表取締役",
    status: "運営中",
    subsidy: [
      {
        amount: "10000000",
        dateOfApproval: "2021-08-25",
        governmentDepartments: "内閣府",
        jointSignatures: ["株式会社プロジェクトサポート"],
        note: "新規事業開発のための補助金",
        subsidyResource: "国庫",
        target: "開発チーム",
        title: "新規事業補助金",
      },
    ],
    updateDate: "2023-07-01",
    workplaceInfo: {
      baseInfos: {
        averageAge: 40.2,
        averageContinuousServiceYears: 10,
        averageContinuousServiceYearsFemale: 8,
        averageContinuousServiceYearsMale: 12,
        averageContinuousServiceYearsType: "中央値",
        monthAveragePredeterminedOvertimeHours: 15,
      },
      compatibilityOfChildcareAndWork: {
        maternityLeaveAcquisitionNum: 10,
        numberOfMaternityLeave: 10,
        numberOfPaternityLeave: 5,
        paternityLeaveAcquisitionNum: 5,
      },
      womenActivityInfos: {
        femaleShareOfManager: 30,
        femaleShareOfOfficers: 15,
        femaleWorkersProportion: 45,
        femaleWorkersProportionType: "割合",
        genderTotalOfManager: 50,
        genderTotalOfOfficers: 20,
      },
    },
  },
  {
    businessItems: ["建設", "不動産"],
    businessSummary: "建設および不動産業を展開する企業。",
    capitalStock: 75000000,
    certification: [
      {
        category: "ISO 14001",
        dateOfApproval: "2018-02-10",
        enterpriseScale: "中小企業",
        expirationDate: "2021-02-09",
        governmentDepartments: "環境認証機構",
        target: "全社",
        title: "環境管理システム",
      },
    ],
    closeCause: "",
    closeDate: "",
    commendation: [
      {
        category: "環境賞",
        dateOfCommendation: "2020-05-30",
        governmentDepartments: "環境省",
        target: "プロジェクトチーム",
        title: "環境保護活動賞",
      },
    ],
    companySizeFemale: 30,
    companySizeMale: 70,
    companyUrl: "https://www.construction-realestate.jp",
    corporateNumber: "3010003094835",
    dateOfEstablishment: "1995-09-10",
    employeeNumber: 100,
    finance: {
      accountingStandards: "日本基準",
      fiscalYearCoverPage: "2021",
      majorShareholders: [
        {
          nameMajorShareholders: "山田太郎",
          shareholdingRatio: 35,
        },
      ],
      managementIndex: [
        {
          capitalStockSummaryOfBusinessResults: 75000000,
          capitalStockSummaryOfBusinessResultsUnitRef: "JPY",
          grossOperatingRevenueSummaryOfBusinessResults: 300000000,
          grossOperatingRevenueSummaryOfBusinessResultsUnitRef: "JPY",
          netAssetsSummaryOfBusinessResults: 200000000,
          netAssetsSummaryOfBusinessResultsUnitRef: "JPY",
          netIncomeLossSummaryOfBusinessResults: 10000000,
          netIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          netPremiumsWrittenSummaryOfBusinessResultsIns: 0,
          netPremiumsWrittenSummaryOfBusinessResultsInsUnitRef: "JPY",
          netSalesSummaryOfBusinessResults: 300000000,
          netSalesSummaryOfBusinessResultsUnitRef: "JPY",
          numberOfEmployees: 100,
          numberOfEmployeesUnitRef: "人",
          operatingRevenue1SummaryOfBusinessResults: 270000000,
          operatingRevenue1SummaryOfBusinessResultsUnitRef: "JPY",
          operatingRevenue2SummaryOfBusinessResults: 30000000,
          operatingRevenue2SummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeLossSummaryOfBusinessResults: 10000000,
          ordinaryIncomeLossSummaryOfBusinessResultsUnitRef: "JPY",
          ordinaryIncomeSummaryOfBusinessResults: 10000000,
          ordinaryIncomeSummaryOfBusinessResultsUnitRef: "JPY",
          period: "2021-04-01 to 2022-03-31",
          totalAssetsSummaryOfBusinessResults: 350000000,
          totalAssetsSummaryOfBusinessResultsUnitRef: "JPY",
        },
      ],
    },
    foundingYear: 1995,
    kana: "ケンセツフドウサン",
    location: "東京都新宿区西新宿２丁目６番１号",
    name: "建設不動産株式会社",
    nameEn: "Construction Real Estate Inc.",
    numberOfActivity: "0",
    patent: [
      {
        applicationDate: "2018-07-15",
        applicationNumber: "2018-345678",
        classifications: [],
        patentType: "意匠",
        title: "高耐震ビル設計",
      },
    ],
    postalCode: "1631305",
    procurement: [
      {
        amount: 15000000,
        dateOfOrder: "2020-03-25",
        governmentDepartments: "国土交通省",
        jointSignatures: ["株式会社アーキテクツ"],
        title: "大型建設プロジェクト",
      },
    ],
    qualificationGrade: "B",
    representativeName: "山田太郎",
    representativePosition: "代表取締役",
    status: "運営中",
    subsidy: [
      {
        amount: "7500000",
        dateOfApproval: "2020-11-10",
        governmentDepartments: "経済産業省",
        jointSignatures: ["株式会社エコ建設"],
        note: "環境保護活動のための補助金",
        subsidyResource: "国庫",
        target: "プロジェクトチーム",
        title: "環境保護補助金",
      },
    ],
    updateDate: "2023-07-01",
    workplaceInfo: {
      baseInfos: {
        averageAge: 38.3,
        averageContinuousServiceYears: 8,
        averageContinuousServiceYearsFemale: 7,
        averageContinuousServiceYearsMale: 9,
        averageContinuousServiceYearsType: "中央値",
        monthAveragePredeterminedOvertimeHours: 20,
      },
      compatibilityOfChildcareAndWork: {
        maternityLeaveAcquisitionNum: 4,
        numberOfMaternityLeave: 4,
        numberOfPaternityLeave: 2,
        paternityLeaveAcquisitionNum: 2,
      },
      womenActivityInfos: {
        femaleShareOfManager: 25,
        femaleShareOfOfficers: 10,
        femaleWorkersProportion: 30,
        femaleWorkersProportionType: "割合",
        genderTotalOfManager: 20,
        genderTotalOfOfficers: 10,
      },
    },
  },
  // さらに7件のサンプルデータを作成するには、上記のようにデータを複製し、各フィールドの値を適宜変更してください
];
